package frc.robot.commands.Vision;

import com.revrobotics.CANSparkMax.IdleMode;

import edu.wpi.first.wpilibj2.command.CommandBase;
import frc.robot.subsystems.Swerve.SwerveDrive;

public class TurnToTarget extends CommandBase{
    
    SwerveDrive m_drive;
    double objectAngle;
    
    public TurnToTarget(SwerveDrive swerveDrive){
        addRequirements(swerveDrive);
        m_drive = swerveDrive;

    }
    
    @Override
    public void initialize() {
        m_drive.setLocked(false);
        m_drive.setIdleModes(IdleMode.kBrake);
        
    }
    // Called every time the scheduler runs while the command is scheduled.
    @Override
    public void execute() {
        if(m_drive.getTarget() != null){
            objectAngle = m_drive.getTarget().getYaw();
            if(objectAngle<0){
                m_drive.setChassisSpeeds(0, 0, 0.1);
            }else{
                m_drive.setChassisSpeeds(0, 0, -0.1);
            }
        }
    }

    // Called once the command ends or is interrupted.
    @Override
    public void end(boolean interrupted) {
        m_drive.setIdleModes(IdleMode.kCoast);
        m_drive.setChassisSpeeds(0, 0, 0);
    }

    // Returns true when the command should end.
    @Override
    public boolean isFinished() {
        if(m_drive.getTarget() != null){
        return Math.abs(objectAngle) <= 2;
        }else{return true;}
    }

    @Override
    public boolean runsWhenDisabled() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
        return false;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
    }

}
