package frc.robot.commands.Vision;

import com.revrobotics.CANSparkMax.IdleMode;

import edu.wpi.first.wpilibj2.command.CommandBase;
import frc.robot.subsystems.Swerve.SwerveDrive;

public class TurnToObject extends CommandBase{
    
    SwerveDrive m_drive;
    double objectAngle;
    double startAngle;
    public TurnToObject(SwerveDrive swerveDrive){
        addRequirements(swerveDrive);
        m_drive = swerveDrive;

    }
    
    @Override
    public void initialize() {
        startAngle = SwerveDrive.m_gyro.getAngle();
        m_drive.setLocked(false);
        m_drive.setIdleModes(IdleMode.kBrake);
    }

    // Called every time the scheduler runs while the command is scheduled.
    @Override
    public void execute() {
        if(m_drive.getColor() != null){
            try {
                objectAngle = m_drive.getColor().getYaw();
            if(objectAngle - startAngle<0){
                m_drive.setChassisSpeeds(0, 0, -0.1);
            }else{
                m_drive.setChassisSpeeds(0, 0, 0.1);
            }    
            } catch (Exception e) {
                System.out.println("he balling");
            }
            
        }
    }

    // Called once the command ends or is interrupted.
    @Override
    public void end(boolean interrupted) {
        m_drive.setChassisSpeeds(0, 0, 0);
    }

    // Returns true when the command should end.
    @Override
    public boolean isFinished() {
        if(m_drive.getColor() != null){
        return Math.abs(objectAngle) <= 1;
        }else{return true;}
    }

    @Override
    public boolean runsWhenDisabled() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
        return false;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
    }

}
